title: Hari Govindarajan
description: QA Automation Leader | AI-Driven Quality Engineering
theme: jekyll-theme-cayman
url: https://harigovindarajan.github.io
github_username: harigovindarajan
linkedin_username: harigovindarajan
linkedin_url: https://www.linkedin.com/in/harigovindarajan/
email: harisudha.g@gmail.com
location: Melbourne

plugins:
  - jekyll-seo-tag
